buildscript {
    ext.kotlin_version = '1.3.50'
    ext.jacocoToolVersion = '0.8.5'
    //TODO remove this block if everything will work fine until Jan 2020
//    ext.kotlin_ann_version = '13.0'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

version '1.0-SNAPSHOT'

apply plugin: 'base'
apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'jacoco'

sourceCompatibility = JavaVersion.VERSION_13
targetCompatibility = JavaVersion.VERSION_13

repositories {
    mavenLocal()
    mavenCentral()

    jcenter()
}

dependencies {
    //stdlib
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    //logging
    implementation 'io.github.microutils:kotlin-logging:+'
    implementation 'io.github.microutils:kotlin-logging-common:+'
    implementation group: 'org.slf4j', name: 'slf4j-log4j12', version: '+'
    implementation group: 'org.slf4j', name: 'slf4j-api', version: '+'
    implementation group: 'log4j', name: 'log4j', version: '+'

    //spek 2
    testImplementation group: 'org.spekframework.spek2', name: 'spek-dsl-jvm', version: '+'
    testImplementation group: 'org.spekframework.spek2', name: 'spek-runner-junit5', version: '+'

}

//TODO remove this block if everything will work fine until Jan 2020
//compileKotlin {
//    kotlinOptions.jvmTarget = "12"
//}
//compileTestKotlin {
//    kotlinOptions.jvmTarget = "12"
//}

//jacoco
jacoco {
    toolVersion = "$jacocoToolVersion"
    reportsDir = file("$buildDir/jacoco") // Jacoco's output root.
}

jacocoTestReport {
    // Tells Jacoco to get its test execution data from JUnit.
    getExecutionData().setFrom(files("$buildDir/jacoco/jacocoTestData.exec"))
    reports {
        csv.enabled = true
        xml.enabled = true
        html.enabled = true
        csv.destination = file("$buildDir/jacoco/jacoco.csv")
        xml.destination = file("$buildDir/jacoco/jacoco.xml")
        html.destination = file("$buildDir/jacoco/html")
    }

    // Tells Jacoco to work on Kotlin code coverage.
    sourceSets(sourceSets.main)
    getSourceDirectories().setFrom(files(sourceSets.main.allSource.srcDirs))
    getClassDirectories().setFrom(files(sourceSets.main.output))
}

//tasks
clean.doLast {
    List<String> files = [
            "${rootDir}/out/",
            "${rootDir}/logs/"
    ]

    files.each {
        println "Delete [$it]"
        file(it).deleteDir()
    }
}

test {
    useJUnitPlatform {
        includeEngines 'spek2'
    }

    jacoco {
        destinationFile = file("$buildDir/jacoco/jacocoTestData.exec")
        classDumpDir = file("$buildDir/jacoco/classpathdumps")
    }
}

test.finalizedBy(jacocoTestReport)
