/*
 * Copyright (c) 2026 krandom contributors
 *
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */
package org.github.krandom.generator.schema;

import java.util.Map;
import java.util.Objects;

/**
 * Produces a schema field value using generation context.
 */
@FunctionalInterface
public interface SchemaValueProvider {

    /**
     * Generates a value for the current schema field.
     *
     * @param context schema generation context
     * @return generated value
     */
    Object generate(SchemaContext context);

    /**
     * Returns the JSON Schema fragment for values produced by this provider.
     *
     * <p>The default is an unconstrained schema ({@code {}}), which keeps
     * {@link Schema#toJsonSchema()} side-effect free for arbitrary lambda providers.
     * Use {@link #withJsonSchema(SchemaValueProvider, Map)} or
     * {@link #withSample(SchemaValueProvider, Object)} when a custom provider can expose a
     * more specific type.
     *
     * @return JSON Schema fragment
     */
    default Map<String, Object> jsonSchema() {
        return JsonSchemaSupport.any();
    }

    /**
     * Wraps a provider with explicit JSON Schema metadata.
     *
     * @param provider   value provider
     * @param jsonSchema JSON Schema fragment returned by the wrapped provider
     * @return provider with schema metadata
     */
    static SchemaValueProvider withJsonSchema(SchemaValueProvider provider, Map<String, ?> jsonSchema) {
        Objects.requireNonNull(provider, "provider must not be null");
        Map<String, Object> schema = JsonSchemaSupport.copyJsonSchema(
            Objects.requireNonNull(jsonSchema, "jsonSchema must not be null"));
        return new SchemaValueProvider() {

            @Override
            public Object generate(SchemaContext context) {
                return provider.generate(context);
            }

            @Override
            public Map<String, Object> jsonSchema() {
                return schema;
            }
        };
    }

    /**
     * Wraps a provider with JSON Schema metadata inferred from a caller-supplied sample.
     *
     * <p>The sample is never generated by the schema exporter; it is only used once when this
     * wrapper is created.
     *
     * @param provider             value provider
     * @param representativeSample sample value used for schema inference
     * @return provider with inferred schema metadata
     */
    static SchemaValueProvider withSample(SchemaValueProvider provider, Object representativeSample) {
        return withJsonSchema(provider, JsonSchemaSupport.infer(representativeSample));
    }
}
