/*
 * Copyright (c) 2026 krandom contributors
 *
 * Licensed under the MIT License. See LICENSE in the project root for license information.
 */
package io.github.frikit.krandom.generator.provider;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/** Generates the checked-in provider reference directly from {@link ProviderCatalog}. */
public final class ProviderCatalogDocumentation {

    private ProviderCatalogDocumentation() {
        throw new UnsupportedOperationException("Utility class");
    }

    /**
     * Writes the rendered provider reference to the requested path.
     *
     * @param args exactly one output path
     * @throws IOException if the output cannot be written
     */
    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("Expected exactly one output path");
        }
        Path output = Path.of(args[0]);
        if (output.getParent() != null) {
            Files.createDirectories(output.getParent());
        }
        Files.writeString(output, render());
    }

    static String render() {
        StringBuilder documentation = new StringBuilder("# Built-in Provider Catalog\n\n");
        documentation.append("> This file is generated by `./gradlew :core:generateProviderCatalogDocumentation`; do not edit it manually.\n\n");
        documentation.append("`ProviderCatalog` is the source of truth for built-in provider keys, aliases, output types, ");
        documentation.append("semantic field mappings, safety metadata, and JSON Schema projections. Custom `ProviderHub` registrations remain ");
        documentation.append("local to that hub.\n\n");
        documentation.append("Safety metadata is conservative: `unclassified` means no claim. A configuration-dependent ");
        documentation.append("claim must be evaluated against the selected `GeneratorConfig` policy.\n\n");
        documentation.append("A classified schema reference exports the same claims through its `x-krandom-safety` ");
        documentation.append("JSON Schema extension, including the selected policy value.\n\n");
        documentation.append("## Hub providers\n\n");
        documentation.append("| Canonical key | Provider type | Hub aliases | Semantic keys | Safety metadata | Schema projections |\n");
        documentation.append("| --- | --- | --- | --- | --- | --- |\n");
        ProviderCatalog.builtIns().forEach(descriptor -> appendDescriptor(documentation, descriptor));

        Set<String> hubKeys = ProviderCatalog.builtIns().stream()
                                                .map(ProviderDescriptor::getKey)
                                                .collect(Collectors.toSet());
        List<ProviderDescriptor<?>> schemaOnly = ProviderCatalog.schemaBuiltIns().stream()
                                                                .filter(descriptor -> !hubKeys.contains(descriptor.getKey()))
                                                                .toList();
        if (!schemaOnly.isEmpty()) {
            documentation.append("\n## Schema-only providers\n\n");
            documentation.append("These projections are available through `FieldLookup` but are not registered in `ProviderHub`.\n\n");
            documentation.append("| Canonical key | Provider type | Safety metadata | Schema projections |\n");
            documentation.append("| --- | --- | --- | --- |\n");
            schemaOnly.forEach(descriptor -> {
                documentation.append("| `")
                             .append(descriptor.getKey())
                             .append("` | `")
                             .append(descriptor.getProviderType().getSimpleName())
                             .append("` | ")
                             .append(safetyMetadata(descriptor))
                             .append(" | ")
                             .append(schemaProjections(descriptor))
                             .append(" |\n");
            });
        }
        return documentation.toString();
    }

    private static void appendDescriptor(StringBuilder documentation, ProviderDescriptor<?> descriptor) {
        documentation.append("| `")
                     .append(descriptor.getKey())
                     .append("` | `")
                     .append(descriptor.getProviderType().getSimpleName())
                     .append("` | ")
                     .append(values(descriptor.getAliases()))
                     .append(" | ")
                     .append(values(descriptor.getSemanticKeys()))
                     .append(" | ")
                     .append(safetyMetadata(descriptor))
                     .append(" | ")
                     .append(schemaProjections(descriptor))
                     .append(" |\n");
    }

    private static String schemaProjections(ProviderDescriptor<?> descriptor) {
        return descriptor.getSchemaProjections().stream()
                         .map(projection -> "`" + projection.getReference() + "`" + aliases(projection.getAliases())
                                            + safetySuffix(projection.getSafetyMetadata()))
                         .collect(Collectors.joining("; ", "", ""));
    }

    private static String safetyMetadata(ProviderDescriptor<?> descriptor) {
        return safetyMetadata(descriptor.getSafetyMetadata());
    }

    private static String safetyMetadata(ProviderSafetyMetadata metadata) {
        if (metadata.equals(ProviderSafetyMetadata.unclassified())) {
            return "`unclassified`";
        }
        return "format: `" + metadata.formatValidity() + "`; checksum: `" + metadata.checksumValidity()
               + "`; semantics: `" + metadata.semanticPlausibility() + "`; test safety: `"
               + metadata.testSafety() + "`";
    }

    private static String safetySuffix(ProviderSafetyMetadata metadata) {
        return metadata.safetyPolicy().isEmpty() ? "" : " (safety: " + safetyMetadata(metadata) + ")";
    }

    private static String aliases(List<String> aliases) {
        return aliases.isEmpty() ? "" : " (aliases: " + values(aliases) + ")";
    }

    private static String values(Iterable<String> values) {
        return java.util.stream.StreamSupport.stream(values.spliterator(), false)
                                               .sorted(Comparator.naturalOrder())
                                               .map(value -> "`" + value + "`")
                                               .collect(Collectors.joining(", "));
    }
}
