name: Run Kotlin Tests
on: [push]

jobs:
  build:
    name: Run Spek2 Test on Ubuntu(latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check where I'm
        working-directory: ${{ github.workspace }}
        run: echo $PWD
      - name: Check files in directory
        run: ls -la
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Running tests
        run: ./gradlew clean check --info --stacktrace --console=plain --max-workers=1 --no-daemon --no-build-cache -Dkotlin.colors.enabled=false
      - name: Codecov
        uses: codecov/codecov-action@v1.0.4
        with:
          # User defined upload name. Visible in Codecov UI
          # Repository uploads token - get it from codecov.io
          token: 31c1b27f-b72a-4c8f-85f9-c7a715b2933b
